[package]
name = "web"
version = "0.0.0"
authors = ["Stefan Kroboth <stefan.kroboth@gmail.com>"]

[dependencies]
rocket = "*"
rocket_codegen = "*"
rand = "0.4"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["handlebars_templates", "tera_templates", "json"]
